# syntax=docker/dockerfile:1.7

# ---- build stage ---------------------------------------------------------
FROM azul-zulu:21-jre AS build
WORKDIR /workspace

# Cache dependencies.
COPY pom.xml ./
COPY .mvn/ .mvn/
COPY mvnw* ./


RUN --mount=type=cache,target=/root/.m2 \
    ./mvnw dependency:go-offline -B
    
# RUN --mount=type=cache,target=/root/.m2 \
#     apt-get update && apt-get install -y --no-install-recommends maven \
#     && mvn -B -q -DskipTests dependency:go-offline

# Build.
COPY src src
RUN --mount=type=cache,target=/root/.m2 \
    ./mvnw package -DskipTests -B
# COPY src src
# RUN --mount=type=cache,target=/root/.m2 \
#     mvn -B -DskipTests package

# ---- runtime stage -------------------------------------------------------
FROM azul-zulu:21-jre
WORKDIR /app

# Create non-root user.
RUN useradd -r -u 1001 -g root neupayment
COPY --from=build /workspace/target/neupayment.jar app.jar
RUN chown -R neupayment:root /app && chmod g+rwX /app

USER 1001
EXPOSE 8080

ENV JAVA_OPTS="-XX:MaxRAMPercentage=75 -XX:+ExitOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom"
ENV SPRING_PROFILES_ACTIVE=prod

HEALTHCHECK --interval=30s --timeout=5s --start-period=40s --retries=3 \
    CMD wget -qO- http://127.0.0.1:8080/actuator/health/liveness || exit 1

ENTRYPOINT ["sh", "-c", "exec java $JAVA_OPTS -jar /app/app.jar"]
